### ISSUE TITLE
Trying to follow README to setup dev environment... errors when running site/manage.py

### ISSUE THREAD

**Issue by pugexpress** [blocher/dailyoffice2019#164]
Hello,

I'm following the README trying to setup the dev environment and I am running into some errors. I have installed all of the prereqs and have created my virtual environment, however I'm seeing this error when trying to run `manage.py collectstatic`. Any advice on how to proceed? Does the README need to be updated or am I missing something?

```sh
(env) myuser@mycomputer site % python manage.py collectstatic
Traceback (most recent call last):
  File "/Users/myuser/Projects/dailyoffice2019/site/manage.py", line 21, in <module>
    main()
  File "/Users/myuser/Projects/dailyoffice2019/site/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/myuser/Projects/dailyoffice2019/site/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/myuser/Projects/dailyoffice2019/site/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/Users/myuser/Projects/dailyoffice2019/site/env/lib/python3.12/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/Users/myuser/Projects/dailyoffice2019/site/env/lib/python3.12/site-packages/django/conf/__init__.py", line 68, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/Projects/dailyoffice2019/site/env/lib/python3.12/site-packages/django/conf/__init__.py", line 166, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/myuser/Projects/dailyoffice2019/site/website/settings.py", line 253, in <module>
    FIRST_BEGINNING_YEAR = int(env("FIRST_BEGINNING_YEAR"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '2018c2j&m2w'
```

I see a similar error when running `manage.py runsslserver` 

**Versions**
MacOS 12
```sh

(env) myuser@mycomputer site % python --version
Python 3.12.7
(env) myuser@mycomputer site % node -v 
v16.20.2
(env) myuser@mycomputer site % brew services list
Name          Status  User          File
memcached     started myuser ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist
postgresql@14 started myuser ~/Library/LaunchAgents/homebrew.mxcl.postgresql@14.plist
unbound       none                  

```

**Comment by george-a-code** [comment]
I’m having similar issues with setup….

**Comment by blocher** [comment]
@george-a-code @pugexpress Sorry for the issues!  I believe this was resolved with https://github.com/blocher/dailyoffice2019/pull/165/files being merged. Please make sure you've copied the change to your own .env file. Let me know if that fixes it.
